# fly.toml app configuration file generated for flydemo-rusty on 2025-07-26T17:12:44-06:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'flydemo-rusty'
primary_region = 'ord'

[build]

[env]
  PORT = '8080'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  size = 'shared-cpu-1x'
